"""

"""

import pickle
import random
import sys
import time


# Function: Slows down text output to output one word at a time, instead of the whole line at once.
def slow_text(text):
    typing_speed = 100  # words per minute
    for letter in text:
        sys.stdout.write(letter)
        sys.stdout.flush()
        time.sleep(random.random() * 10.0 / typing_speed)
    print('')


# Function: Slows down text output to output only one line each time before requiring the user to press 'enter'
def continue_text(lines: list):
    for line in lines:
        slow_text(line)
        # Forces the user to press 'enter' after each line
        get_user_input([""])


# Function: Takes input from the user. If the user inputs something invalid, it loops, else it returns the input.
def get_user_input(valid_input: list):
    while True:
        try:
            user_entered = input()
        except EOFError:
            sys.exit(0)

        if user_entered not in valid_input:
            print("Invalid input. Please use one of the following inputs:\n")
            print(valid_input)

        else:
            return user_entered


# Function: Iterates over the options and allocates a number to each response
def create_response(options: list):
    for index, option in enumerate(options):
        print(str(index) + ". " + option[0])

    valid_inputs = [str(num) for num in range(len(options))]
    option_index = int(get_user_input(valid_inputs))

    return options[option_index][1]


# Function: Sets the initial page to 1, keeps turning pages until current page is none.
def play_story(game: dict):
    current_page = 1

    while current_page is not None:
        page = game.get(current_page, None)

        if page is None:
            break

        continue_text(page.get('Text', []))

        options = page.get('Options', [])
        if len(options) == 0:
            break

        current_page = create_response(options)


# Loads the chapter (generated by running a game file) using pickle import then reads through its pages.
if __name__ == '__main__':
    try:
        with open('current_game.ch', 'rb') as chapter:
            story = pickle.load(chapter)
    except (OSError, EOFError, pickle.UnpicklingError):
        story = None

    if not isinstance(story, dict):
        print("No valid game file found. Run a game file (e.g. 'template.py') to generate 'current_game.ch'.")
        sys.exit(1)

    play_story(story)
