import pickle
import runpy
import sys
from os import path, remove

from engine import play_story

CHAPTER_FILE = 'current_game.ch'

MENU_PROMPT = ('Welcome to the Conquest of Munster Word Game \n'
               'Please Select a number from the following options \n'
               '1. Enter Game File to Play \n'
               '2. Start Game\n'
               '3. Quit \n'
               '>>>> ')


# menu option for running of game
def show_menu():
    # while statement to handle invalid data type entry
    while True:
        try:
            choice = int(input(MENU_PROMPT))
        # for handling of string data instead of numeric options
        except ValueError:
            print("Please enter valid options only")
            continue
        except EOFError:
            return

        if 0 < choice <= 3:
            # once user has selected an option, the program user choice is passed to the get choice method
            try:
                get_choice(choice)
            except EOFError:
                return
        # if a number less than 1 or greater than 3 is chosen the menu is shown again


# handles the users choice
def get_choice(choice):
    if choice == 1:  # call on program to run default template file
        game_name = input("Please enter file name of the game you wish to play")
        # check if game file exists in directory
        if path.exists(game_name):
            load_game_file(game_name)
        else:
            print("That game file does not exist")
    elif choice == 2:  # call on program to request game file name
        story = load_chapter()
        if story is None:
            print("Please Select Option 1 and load valid game file")
        else:
            play_story(story)
            # a finished run must not leave a stale save behind for the next run
            clear_chapter()
    elif choice == 3:  # calls on program to exit as per users request
        print("You have chosen to finish the game thanks for playing")
        sys.exit()


# Function: Runs a game file in its own namespace so it cannot pollute the menu state.
def load_game_file(game_name):
    clear_chapter()
    try:
        runpy.run_path(game_name)
    except (Exception, SystemExit):
        print("That game file could not be loaded")


# Function: Reads the chapter file generated by a game file, returns None when it is missing or invalid.
def load_chapter():
    try:
        with open(CHAPTER_FILE, 'rb') as chapter:
            story = pickle.load(chapter)
    except Exception:
        return None

    if not isinstance(story, dict):
        return None

    return story


# Function: Removes the saved chapter so old games cannot leak into a fresh run.
def clear_chapter():
    if path.exists(CHAPTER_FILE):
        remove(CHAPTER_FILE)


def main():
    show_menu()


if __name__ == '__main__':
    main()
